version: "3"
services:
  nosql-db:
    image: mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  courses:
    build:
      dockerfile: Dockerfile
      context: ./courses
    container_name: courses
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/courses/node_modules

    env_file:
      - ./courses/.env

    nginx-proxy:
      build:
        dockerfile: Dockerfile
        context: ./proxy
      depends_on:
        - courses
      ports:
        - 80:80